Memic/Controllers/CallApiController.cs
using IdentityModel.Client;
using Newtonsoft.Json.Linq;
using System;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Memic.Controllers
{
    public class CallApiController : Controller
    {
        // GET: CallApi/ClientCredentials

        public async Task<ActionResult> ClientCredentials()
        {
            var response = await GetTokenAsync();
            var result = await CallApi(response.AccessToken);

            ViewBag.Json = result;
            return View("ShowApiResult");
        }

        // GET: CallApi/UserCredentials
        public async Task<ActionResult> UserCredentials()
        {
            var user = User as ClaimsPrincipal;
            var token = user.FindFirst("access_token").Value;
            var result = await CallApi(token);

            ViewBag.Json = result;
            return View("ShowApiResult");
        }

        private async Task<TokenResponse> GetTokenAsync()
        {

            var client = new TokenClient(IdentityServerConfig.Endpoint.IdentityServerTokenUri,
            "mvc_service",
            "secret");

            return await client.RequestClientCredentialsAsync("memicApi");
        }
        private async Task<string> CallApi(string token)
        {
            var client = new HttpClient();
            client.SetBearerToken(token);
            var json = await client.GetStringAsync(IdentityServerConfig.Endpoint.APIIdentityUri);
            return JArray.Parse(json).ToString();
        }



    }
}

Memic/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Thinktecture.IdentityModel.Mvc;

namespace Memic.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult Identity()
        {
            return View((User as ClaimsPrincipal).Claims);
        }

        [ResourceAuthorize("Read", "ContactDetails")]
        [HandleForbidden]
        public ActionResult Contact()
        {
            ViewBag.Message = "My Contact Information:";

            return View();
        }
        [ResourceAuthorize("Write", "UpdateData")]
        [HandleForbidden]
        public ActionResult UpdateData()
        {

            //if (!HttpContext.CheckAccess("Write", "UpdateData", "more data"))
            //{
            //    // either 401 or 403 based on authentication state
            //    return this.AccessDenied();
            //}

            ViewBag.Message = "Allowed to Updata data";

            return View();
        }
        public ActionResult Logout()
        {
            Request.GetOwinContext().Authentication.SignOut();
            return Redirect("/");
        }

    }
}

Memic/Views/CallApi/ShowApiResult.cshtml
@{
    ViewBag.Title = "ShowApiResult";
}



<h3>Client Authorization - Not User Authentication</h3>
<div class="well">This Application has access to the API, but the world does not.  If you go to the API directly at
    <a href="@IdentityServerConfig.Endpoint.APIIdentityUri">@IdentityServerConfig.Endpoint.APIIdentityUri</a>, you should be denied.
    <br /><br />
    If we want to have User Authentication for this API,  we place an [Authorize] decorator above the controller.<br /><br />
    Or for more control based on user roles,  we add [ResourceAuthorize("Write", "MyAPI")] and  [HandleForbidden] decorators above the controller and add the task to the AuthorizationManager.
</div>
<h3>Result</h3>
<pre>@ViewBag.Json</pre>

Memic/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<h3>@ViewBag.Message</h3>

<address>
    John Seeman<br />
    <br />
    <abbr title="Phone">Phone: </abbr>
    813.833.0670
</address>

Memic/Views/Home/Forbidden.cshtml
@{
    ViewBag.Title = "Forbidden";
}

<h2>Your role is not authorized for this action.</h2>

<div class="well">
    Go To the 'AuthorizationManager' class under root and Comment Line 44 and Uncomment Line 45.
    <br /><br />
    This will allow the 'Manager' role to access this resource. 
</div>

Memic/Views/Home/Identity.cshtml
@model IEnumerable<System.Security.Claims.Claim>

<h3>User Identity</h3>
<dl>
    @foreach (var claim in Model)
    {
        <dt>@claim.Type</dt>
        <dd>@claim.Value</dd>
    }
</dl>

Memic/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Memic Web Token Application";
}

<div class="jumbotron">
    <h2>Memic Web Token Application</h2>
    <ol style="font-weight:bold; font-size:larger; line-height:30px">
        <li>Click on 'Identity' in the menu above </li>
        <li>
            Login with:
            <ul style="list-style-type: none">
                <li>Username: Larry</li>
                <li>Password: secret</li>
            </ul>
        </li>
        <li>Allow All Permissions</li>
        <li>View the Web Token and the User Claims</li>
    </ol>   
</div>

Memic/Views/Home/UpdateData.cshtml
@{
    ViewBag.Title = "UpdateData";
}

<h2>Allow Update Data</h2>

Memic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Memic Web Token Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Memic Web Token Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Identity", "Identity", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Update Data", "UpdateData", "Home")</li>
                    <li>@Html.ActionLink("Call API", "ClientCredentials", "CallApi")</li>
                    <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>